language: node_js
node_js:
  - 10

addons:
  chrome: stable

cache:
  directories:
    - ~/.npm
    - node_modules

install:
  yarn

before_script:
  - greenkeeper-lockfile-update
  - git add package.json
  - git commit --amend --no-edit

notifications:
  email: false

script:
  - yarn check --integrity
  - yarn typecheck
  - yarn test
  - cat coverage/lcov/lcovonly | yarn coveralls

after_script:
  - greenkeeper-lockfile-upload

deploy:
  provider: script
  skip_cleanup: true
  script: tasks/deploy
